version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 18
  build:
    commands:
      - npm run build
      - export BUCKET=<OUTPUT BUCKET>     
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
