name: Deploy SAM Application

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and Deploy SAM Application
        run: |
          sam validate
          sam build

          # Deploy each function
          sam deploy --stack-name LoginFunction --region us-east-1 --capabilities CAPABILITY_IAM
          sam deploy --stack-name SuggestionsFunction --region us-east-1 --capabilities CAPABILITY_IAM
          # Repeat for other functions
