name: Deploy SAM Application

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install SAM CLI
        run: |
          curl -L -o install-aws-cli.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
          chmod +x /tmp/install-aws-cli.sh

      - name: Build and Deploy SAM Application
        run: |
          sam validate
          sam build

          # Deploy each function
          sam deploy --stack-name LoginFunction --region us-east-1 --capabilities CAPABILITY_IAM
          sam deploy --stack-name SuggestionsFunction --region us-east-1 --capabilities CAPABILITY_IAM
          # Repeat for other functions

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
